name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  app_links: ^3.4.3
  crypto: ^3.0.6
  csv: ^6.0.0
  encrypt: ^5.0.3
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  mobile_scanner: ^3.5.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  share_plus: ^11.1.0
  supabase_flutter: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logoR.png
    - lib/assets/logoName1.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logoR.png" # your icon
  adaptive_icon_background: "#118e69"    # background color for Android adaptive icons
  adaptive_icon_foreground: "lib/assets/logoR.png"

flutter_native_splash:
  color: "#118e69"
  image: lib/assets/logoR.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: false