name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  app_links: ^3.4.3
  crypto: ^3.0.6
  csv: ^6.0.0
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  share_plus: ^11.1.0
  supabase_flutter: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logoR.png
    - lib/assets/logoName1.png
